#! Dockerfile_user_code

FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# Install libraries without cache to reduce image size
RUN pip install --no-cache-dir \
    dagster==1.8.9 \
    dagster-postgres==0.24.9 \
    dagster-docker==0.24.9

# Set the working directory
WORKDIR /opt/dagster/app

# Copy workspace configuration
COPY workspace.yaml /opt/dagster/app/workspace.yaml

# Set environment variables
ENV PATH="/usr/local/bin:${PATH}"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_ROOT_USER_ACTION=ignore

# Expose the port for the gRPC server
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD sh -c "dagster api grpc -h 0.0.0.0 -p 4000 -f $REPO_FILE"
