
# FROM python:3.10-slim

# # Change working directory
# WORKDIR /usr/src/app
# ENV DAGSTER_HOME=/usr/src/app

# # Install dependencies
# # Copy necessary configuration and requirement files
# COPY dagster.yaml workspace.yaml requirements.txt ./
# # Upgrade pip and install the necessary Python packages
# RUN pip install --upgrade pip \
#     && pip install -r requirements.txt \
#     dagster \
#     dagster-webserver \
#     dagster-postgres \
#     dagster-aws

# # Copy the rest of the project files
# # COPY . .

# # Expose port 3000 for the webserver
# EXPOSE 3000

# # Run the Dagster development server on startup
# CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME